import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import'./style.css';
type Any=Record<string,any>;type View='runs'|'topology'|'runtime'|'legacy';
const api=async(path:string,init?:RequestInit)=>{const response=await fetch(path,{cache:'no-store',...init});if(!response.ok)throw Error(await response.text());return response.json()};
const csrf=()=>document.cookie.split('; ').find(value=>value.startsWith('workbench_csrf='))?.split('=')[1]||'';
const mergeEvents=(old:Any[],added:Any[])=>{const values=new Map(old.map(event=>[`${event.nodeId}:${event.eventId}`,event]));for(const event of added)values.set(`${event.nodeId}:${event.eventId}`,event);return[...values.values()].sort((a,b)=>a.timestamp-b.timestamp).slice(-2000)};
function App(){
 const[view,setView]=useState<View>('runs'),[snapshot,setSnapshot]=useState<Any>({}),[runs,setRuns]=useState<Any[]>([]),[events,setEvents]=useState<Any[]>([]),[error,setError]=useState('');
 const[runOffset,setRunOffset]=useState(0),[runStatus,setRunStatus]=useState(''),[selectedRun,setSelectedRun]=useState(''),[kind,setKind]=useState(''),[node,setNode]=useState(''),[eventStatus,setEventStatus]=useState('');
 const[logs,setLogs]=useState<Any|null>(null),[driverSecrets,setDriverSecrets]=useState<Record<string,Any>>({});
 const load=async(offset=runOffset,status=runStatus)=>{try{const query=new URLSearchParams({limit:'50',offset:String(offset)});if(status)query.set('status',status);const[s,r]=await Promise.all([api('/api/snapshot'),api(`/api/runs?${query}`)]);setSnapshot(s);setRuns(r.result||[]);setError('')}catch(e){setError(String(e))}};
 useEffect(()=>{load(0,runStatus);setRunOffset(0)},[runStatus]);
 useEffect(()=>{const timer=setInterval(()=>load(),5000);const source=new EventSource('/api/events?cursor=0');source.addEventListener('observations',event=>{const value=JSON.parse((event as MessageEvent).data);setEvents(old=>mergeEvents(old,value.events||[]))});return()=>{clearInterval(timer);source.close()}},[runOffset,runStatus]);
 const inspectRun=async(runId:string)=>{setSelectedRun(runId);try{const value=await api(`/api/observations?runId=${encodeURIComponent(runId)}&limit=1000`);setEvents(old=>mergeEvents(old,value.result?.events||[]))}catch(e){setError(String(e))}};
 const post=async(body:Any)=>api('/api/operator/action',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf()},body:JSON.stringify(body)});
 const normal=async(action:string,target:string,extra:Any={})=>{if(!confirm(`Confirm ${action} ${target}?`))return;const result=await post({action,target,...extra});await load();return result.result};
 const force=async(action:string,target:string,executorId?:string)=>{const reason=prompt(`Reason for ${action} ${target}`);if(!reason||!confirm(`Confirm ${action} ${target}?`))return;const headers={'Content-Type':'application/json','X-CSRF-Token':csrf()};const nonce=await api('/api/operator/nonce',{method:'POST',headers,body:JSON.stringify({action,target,reason,confirmed:true})});await api('/api/operator/action',{method:'POST',headers,body:JSON.stringify({actionNonce:nonce.result.actionNonce,action,target,executorId})});load()};
 const showLogs=async(executorId:string,processId:string)=>{try{setLogs(await api(`/api/logs?executorId=${encodeURIComponent(executorId)}&processId=${encodeURIComponent(processId)}&tail=500`))}catch(e){setError(String(e))}};
 const filtered=useMemo(()=>events.filter(event=>(!selectedRun||event.runId===selectedRun)&&(!kind||event.kind===kind)&&(!node||event.nodeId===node)&&(!eventStatus||event.status===eventStatus)),[events,selectedRun,kind,node,eventStatus]);
 const options=(field:string)=>[...new Set(events.map(event=>event[field]).filter(Boolean))].sort();
 const acquire=async(resource:string)=>{const lease=await normal('driver-acquire',resource);if(lease)setDriverSecrets(old=>({...old,[resource]:lease}))};
 const release=async(resource:string)=>{const lease=driverSecrets[resource];if(!lease)return;await normal('driver-release',resource,{owner:lease.owner,driverToken:lease.token});setDriverSecrets(old=>{const next={...old};delete next[resource];return next})};
 const handoff=async(resource:string)=>{const lease=driverSecrets[resource],target=prompt(`Handoff ${resource} to owner`);if(!lease||!target)return;await normal('driver-handoff',resource,{owner:lease.owner,driverToken:lease.token,handoffTarget:target});setDriverSecrets(old=>{const next={...old};delete next[resource];return next})};
 return <><header><h1>Distributed Workbench</h1><nav>{(['runs','topology','runtime','legacy']as View[]).map(name=><button key={name} className={view===name?'active':''} onClick={()=>setView(name)}>{name}</button>)}</nav></header><main>
 {error&&<section className="error">{error}<button onClick={()=>setError('')}>Dismiss</button></section>}
 {view==='runs'&&<><div className="toolbar"><h2>Runs</h2><select aria-label="Run status" value={runStatus} onChange={event=>setRunStatus(event.target.value)}><option value="">All statuses</option>{['running','completed','cancelled','interrupted'].map(value=><option key={value}>{value}</option>)}</select></div>{runs.map(run=><section key={run.runId} className={`card selectable ${selectedRun===run.runId?'selected':''}`} onClick={()=>inspectRun(run.runId)}><b>{run.targetSummary}</b><span>{run.status} · {run.health}</span><small>{run.runId}</small></section>)}<div className="pager"><button disabled={runOffset===0} onClick={()=>{const value=Math.max(0,runOffset-50);setRunOffset(value);load(value)}}>Previous</button><span>Offset {runOffset}</span><button disabled={runs.length<50} onClick={()=>{const value=runOffset+50;setRunOffset(value);load(value)}}>Next</button></div>{selectedRun&&<section className="card"><div className="toolbar"><h2>Run waterfall</h2><button onClick={()=>setSelectedRun('')}>Close</button></div><div className="filters"><select aria-label="Event kind" value={kind} onChange={e=>setKind(e.target.value)}><option value="">All kinds</option>{options('kind').map(value=><option key={value}>{value}</option>)}</select><select aria-label="Event node" value={node} onChange={e=>setNode(e.target.value)}><option value="">All nodes</option>{options('nodeId').map(value=><option key={value}>{value}</option>)}</select><select aria-label="Event status" value={eventStatus} onChange={e=>setEventStatus(e.target.value)}><option value="">All event statuses</option>{options('status').map(value=><option key={value}>{value}</option>)}</select></div>{filtered.map(event=><div key={`${event.nodeId}:${event.eventId}`} className="lane"><i>{event.nodeId}</i><span>{event.kind} / {event.name}</span><span>{event.status}</span><span>{event.durationMs??0}ms</span></div>)}</section>}</>}
 {view==='topology'&&<section className="grid"><Card title="Controllers / peer health" value={snapshot.controllers}/><Card title="Executors / capabilities" value={snapshot.executors}/><Card title="Generations" value={snapshot.generations}/></section>}
 {view==='runtime'&&<><Card title="Sessions" value={snapshot.sessions}/><section className="card"><h2>Driver sessions</h2>{(snapshot.sessions||[]).map((session:Any)=>{const lease=(snapshot.leases||[]).find((item:Any)=>item.resource===session.id);return <div className="row" key={session.id}><code>{session.id}</code><span>{lease?`owned by ${lease.owner}`:'available'}</span>{!lease&&<button onClick={()=>acquire(session.id)}>Acquire</button>}{driverSecrets[session.id]&&<><button onClick={()=>handoff(session.id)}>Handoff</button><button onClick={()=>release(session.id)}>Release</button></>}</div>})}</section><Card title="Leases and ports" value={{leases:snapshot.leases,ports:snapshot.ports}}/><section className="card"><h2>Approvals</h2>{(snapshot.approvals||[]).map((approval:Any)=><div className="row" key={approval.id}><code>{approval.id}</code><span>{approval.state} · {approval.digest}</span>{approval.state==='pending'&&<><button onClick={()=>normal('approval-approve',approval.id)}>Approve</button><button onClick={()=>normal('approval-revoke',approval.id)}>Revoke</button></>}</div>)}</section><section className="card"><h2>Tasks</h2>{(snapshot.tasks||[]).map((task:Any)=><div key={task.id} className="row"><code>{task.id}</code><span>{task.state}</span>{task.state==='failed'&&<button onClick={()=>normal('retry-task',task.id)}>Retry</button>}{!['succeeded','failed','cancelled','failed-to-cancel'].includes(task.state)&&<button onClick={()=>force('cancel-task',task.id)}>Cancel…</button>}</div>)}</section><section className="card"><h2>Processes</h2>{(snapshot.processNodes||[]).flatMap((entry:Any)=>entry.processes.map((process:Any)=><div key={`${entry.executorId}:${process.id}`} className="row"><code>{entry.executorId} / {process.id}</code><span>{process.state} · {process.readiness?.state}</span><button onClick={()=>showLogs(entry.executorId,process.id)}>Logs</button>{process.restartable&&<button onClick={()=>normal('restart-process',process.id,{executorId:entry.executorId})}>Restart</button>}{process.state==='running'&&<button onClick={()=>force('stop-process',process.id,entry.executorId)}>Stop…</button>}</div>))}</section>{logs&&<section className="card logs"><div className="toolbar"><h2>Process logs · {logs.processId}</h2><button onClick={()=>setLogs(null)}>Close</button></div><pre>{(logs.lines||[]).join('\n')}</pre></section>}</>}
 {view==='legacy'&&<><Card title="Legacy task summaries (Runs are never inferred)" value={snapshot.tasks}/><Card title="Unscoped observations" value={events.filter(event=>!event.runId)}/></>}
 </main></>;
}
function Card({title,value}:{title:string,value:Any}){return <section className="card"><h2>{title}</h2><pre>{JSON.stringify(value||[],null,2)}</pre></section>}
createRoot(document.getElementById('root')!).render(<App/>);
